spring.application.name=TheaterSeatReservationSystem
spring.datasource.url=jdbc:postgresql://localhost:5432/bancodeteste
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true


spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.idle-timeout=10000
spring.web.error.include-stacktrace=never


stripe.api.key=${STRIPE_SECRET_KEY}
stripe.public.key=${STRIPE_PUBLIC_KEY}
api.security.token.secret=${JWT_SECRET}
cors.allowed_origin=${CORS_ALLOWED_ORIGIN}
cors.allowed_origin=${CORS_ALLOWED_ORIGIN}
