CREATE TABLE  seatType (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    price DECIMAL (10, 2) NOT NULL
);

ALTER TABLE seat ADD COLUMN type_id INTEGER;

ALTER TABLE seat ADD CONSTRAINT fk_seat_type FOREIGN KEY (type_id) REFERENCES seatType(id);