ALTER TABLE movie ADD COLUMN synopsis VARCHAR(500) NOT NULL;
ALTER TABLE movie ADD COLUMN genre VARCHAR (100) NOT NULL ;
ALTER TABLE movie ADD COLUMN classification INTEGER NOT NULL;
ALTER TABLE movie ADD COLUMN poster_url VARCHAR (150) NOT NULL;